### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by euglevi** [ghostty-org/ghostty#3366]
I have been trying to build Ghostty from source in Debian using a Zig bundle, 0.13 version. When I run `zig build -p $HOME/.local -Doptimize=ReleaseFast ` in the directory of the source code, I get the following lines of error:

```
/home/eugenio/ghostty-source/build.zig.zon:8:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/mitchellh/libxev/archive/db6a52bafadf00360e675fefa7926e8e6c0e9931.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:17:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/mitchellh/zig-objc/archive/9b8ba849b0f58fe207ecd6ab7c147af55b17556e.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:21:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/mitchellh/zig-js/archive/d0b8b0a57c52fbc89f9d9fecba75ca29da7dd7d1.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:25:20: error: unable to connect to server: UnknownHostName
            .url = "https://deps.files.ghostty.org/ziglyph-b89d43d1e3fb01b6074bc1f7fc980324b04d26a5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:52:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/mbadolato/iTerm2-Color-Schemes/archive/d6c42066b3045292e0b1154ad84ff22d6863ebf7.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:56:20: error: unable to discover remote git server capabilities: UnknownHostName
            .url = "git+https://github.com/rockorager/libvaxis/?ref=main#6d729a2dc3b934818dffe06d2ba3ce02841ed74b",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:60:20: error: unable to discover remote git server capabilities: UnknownHostName
            .url = "git+https://github.com/natecraddock/zf/?ref=main#ed99ca18b02dda052e20ba467e90b623c04690dd",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/build.zig.zon:64:20: error: unable to discover remote git server capabilities: UnknownHostName
            .url = "git+https://github.com/vancluever/z2d?ref=v0.4.0#4638bb02a9dc41cc2fb811f092811f6a951c752a",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/spirv-cross/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/KhronosGroup/SPIRV-Cross/archive/476f384eb7d9e48613c45179e502a15ab95b6b49.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/freetype/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/freetype/freetype/archive/refs/tags/VER-2-13-2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/sentry/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/getsentry/sentry-native/archive/refs/tags/0.7.8.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/breakpad/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/getsentry/breakpad/archive/b99f444ba5f6b98cac261cbb391d8766b34a5918.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/zlib/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/wuffs/build.zig.zon:6:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/google/wuffs/archive/refs/tags/v0.4.0-alpha.8.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/harfbuzz/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/harfbuzz/harfbuzz/archive/refs/tags/8.4.0.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/oniguruma/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/kkos/oniguruma/archive/refs/tags/v6.9.9.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/libpng/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/glennrp/libpng/archive/refs/tags/v1.6.43.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/fontconfig/build.zig.zon:6:20: error: unable to connect to server: UnknownHostName
            .url = "https://deps.files.ghostty.org/fontconfig-2.14.2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/utfcpp/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/nemtrif/utfcpp/archive/refs/tags/v4.0.5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/libxml2/build.zig.zon:6:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/GNOME/libxml2/archive/refs/tags/v2.11.5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/glslang/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/KhronosGroup/glslang/archive/refs/tags/14.2.0.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/highway/build.zig.zon:7:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/google/highway/archive/refs/tags/1.1.0.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/eugenio/ghostty-source/pkg/cimgui/build.zig.zon:9:20: error: unable to connect to server: UnknownHostName
            .url = "https://github.com/ocornut/imgui/archive/e391fe2e66eb1c96b1624ae8444dc64c23146ef4.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

What do they mean? Sorry but I am not familiar with zig. Thank you very much!

**Comment by jwikiera** [comment]
I get similar timeouts on Arch:
```
.cache/yay/ghostty-git/src/ghostty/build.zig.zon:25:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://deps.files.ghostty.org/ziglyph-b89d43d1e3fb01b6074bc1f7fc980324b04d26a5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.cache/yay/ghostty-git/src/ghostty/pkg/fontconfig/build.zig.zon:6:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://deps.files.ghostty.org/fontconfig-2.14.2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.cache/yay/ghostty-git/src/tmp/p/1220c72c1697dd9008461ead702997a15d8a1c5810247f02e7983b9f74c6c6e4c087/build.zig.zon:11:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Firefox gets the files just fine, while wget times out.

**Comment by euglevi** [comment]
I seem to get slightly different message errors: `UnknownHostName` rather than `ConnectionTimedOut'. But I confirm that Firefox gets the files just fine.

**Comment by miekg** [comment]
hmmm , I get a different build fail:

~~~
% zig build -Doptimize=ReleaseFast                                                                                       ~/src/github.com/ghostty-org/ghostty tags/v1.0.0

thread 306043 panic: reached unreachable code
Panicked during a panic. Aborting.
~~~

On Asahi Linux fedora 40, zig 0.13

**Comment by mynvimconfigs** [comment]
Try changing the network you are using. In my case, using a different Internet connection allowed 
 https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz to be properly fetched, for example. (My problem was similar to 
 jwikiera's --- the file could be downloaded using a browser, but not using the terminal).

I am still trying to compile, but I think this part was solved in my case.

**Comment by euglevi** [comment]
It also solved my case. Moving away from a cable ethernet connection to wifi solved the issue.

**Comment by fabolous005** [comment]
I think due to amount of concurrent connections some library in the background limits some of these connections, resulting in these errors.
For me just rerunning the fetch always solved it...

**Comment by sfrique** [comment]
it seems codeberg.org is offline for me as well.

**Comment by mitchellh** [comment]
Environmental issue as noted.

**Comment by dradtke** [comment]
I'm getting the same error still on Ubuntu:

```sh
$ zig build -Doptimize=ReleaseFast
/home/dradtke/workspace/ghostty/build.zig.zon:25:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://deps.files.ghostty.org/ziglyph-b89d43d1e3fb01b6074bc1f7fc980324b04d26a5.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dradtke/.cache/zig/p/12200df4ebeaed45de26cb2c9f3b6f3746d8013b604e035dae658f86f586c8c91d2f/build.zig.zon:11:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dradtke/workspace/ghostty/pkg/fontconfig/build.zig.zon:6:20: error: unable to connect to server: ConnectionTimedOut
            .url = "https://deps.files.ghostty.org/fontconfig-2.14.2.tar.gz",
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

What's the workaround? I'm on a desktop so I can't easily switch networks.

For example, https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz downloads just fine for me in Firefox and `curl`, but fails with `wget` and `zig build`.

**Comment by tao12345666333** [comment]
I encountered another problem on Fedora 39

```
(⎈|moe-aks:default)➜  ghostty git:(main) zig build -p $HOME/.local -Doptimize=ReleaseFast

/home/tao/workspace/ghostty/build.zig:148:20: error: expected 'while' or 'for', found 'else'
            inline else => |code| {
                   ^

```

**Comment by jcollie** [comment]
> Fedora 39

What version of Zig? Ghostty _only_ compiles with version 0.13.0 so it looks like you're using an older version.

**Comment by jcollie** [comment]
> I encountered another problem on Fedora 39

Also, it's bad form to add unrelated comments to a closed issue like this. Please start a new discussion if you're still having problems.

**Comment by FlanderJam** [comment]
Running into this issue on Ubuntu 24.04.2 LTS, zig 0.13.0, and trying to build from tag V1.1.0.

I'm receiving a TlsInitializationFailed error when reaching out to get the [codeberg tar](https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz).

When I tried to go this site in my browser, it also failed to load and Codeberg served a webpage saying that I had been rate limited because my activity was suspicious.

I don't know that there is a fix for this, and I'm not trying to revive this thread. I just wanted to post some additional information for anyone else who runs into this issue.

I'll just try to build again later after my rate limit has reset, or try from a different network like other posters have mentioned.

**Comment by mitchellh** [comment]
Yes, Codeberg is down (DDoS). We have plans to remirror all our dependencies.

**Comment by gulducat** [comment]
I had a persistent `ConnectionTimedOut`, and like dradtke, for me it was ipv6-related.

My lazy bypass was to force ipv4 with /etc/hosts:

```
h=deps.files.ghostty.org; echo $(dig +short $h) $h | sudo tee -a /etc/hosts
```

Just remember that can cause problems later if the live DNS changes.
