### ISSUE TITLE
Regression: glfw build on Mac is failing to build

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#6727]
I just want a place to track this. If you remove all caches on macOS and build GLFW since https://github.com/ghostty-org/ghostty/commit/221f905a1c5332a96f04918ea87d1c85a05af035 you get errors like the following:

```
zig build -Dapp-runtime=glfw
```

```
install
└─ install ghostty
   └─ zig build-exe ghostty Debug aarch64-macos.13.0 2 errors
pkg/macos/foundation/c.zig:1:15: error: C import failed: FileNotFound
pub const c = @cImport({
              ^~~~~~~~
pkg/macos/text/c.zig:1:15: error: C import failed: FileNotFound
pub const c = @cImport({
              ^~~~~~~~
error: the following command failed with 2 compilation errors:
```

I have no idea why this is happening yet.

Note this applies _only to GLFW builds_. Standard libghostty and Swift builds (plain `zig build`) work fine.

Introduced by https://github.com/ghostty-org/ghostty/commit/221f905a1c5332a96f04918ea87d1c85a05af035#diff-201b1fb9d546eb76c303bb5e2c3bc04204496e3e4e2d8c68dbd7b7ecab440a03
